# https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc
_extends: github:jenkinsci/.github:/.github/release-drafter.yml
tag-template: nexus-artifact-uploader-$NEXT_MINOR_VERSION
